;SUMADOR DE 3 BITS QUE INGRESAN DESDE EL PORTA
;EL RESULTADO VA A SER ALMACENADO EN PORTB
    
#INCLUDE<P18F4550.INC>

;ETIQUETAS
    
#DEFINE COPY H'02'
#DEFINE COPY2 H'03'    
    
;ORIGEN EN MEM:
    ORG .0
    
SETTINGS
    CLRF PORTA
    SETF TRISA	    ;LOS PINES RA[0,1,2,3,4,5] SON INPUTS
    MOVLW H'0F'
    MOVWF ADCON1    ;LOS PORTS A,B,E SON DIGITALES
    MOVLW .7	
    MOVWF CMCON	    ;EL MOD COMPARADOR CONECTADO EN PORTA Y E ESTA OFF
    
    CLRF TRISB	    ;TODOS LOS PINES DEL PB SON OUTS
    CLRF LATB
    
MAIN
    
    MOVFF PORTA, COPY ;LO QUE TENGA PORTA LO TENDRA COPY Y COPY2
    MOVFF PORTA, COPY2
    
    MOVLW B'00111000'
    ANDWF COPY,F    ;COPY ES EL PORTA QUE VAMOS A MASKEAR COPY=56
    RRNCF COPY,F    ;PA='0011 1111' COPY=28 B'0001 1100'
    RRNCF COPY,F    ;PA=16 COPY=14 B'0000 1110'
    RRNCF COPY,F    ;PA=16 COPY=7 B'0000 0111'
    
    MOVLW B'00000111'
    ANDWF COPY2,F	;COPY2 = '0011 1111' -> COPY2= B'0000 0111'
    
    MOVF COPY2,W	    ;MOVEMOS DE COPY2 A W. W= 7
    ADDWF COPY,W    ;W= .7 + .7 -> W=14
    MOVWF LATB	    ; MOVEMOS EL .14 AL PORTB
    GOTO MAIN
    END
    


